### ISSUE TITLE
Stream not loading

### ISSUE THREAD

**Issue by pcdeem** [aussieaddons/plugin.video.afl-video#2612]
Just started the plugin and the stream doesn't load.
All the previous JLT streams worked well.
After a minute a message pops up about items failing to play.
Does this have anything to do with a new message I just saw in the AFL live app asking me what my location was?
The app updated on the 10th of March and I haven't run it since then but I haven't seen this before from the app.

Thanks

**Comment by andybotting** [comment]
See issue #2611

**Comment by hawksta** [comment]
Not sure what the fix for this is.  Can you please explain?

**Comment by glennguy** [comment]
Fixed in e429beb. Update to v1.9.1

**Comment by 24Clayton** [comment]
Hi, I'm still having issues getting v1.9.1 to work for live streams. It tries to play but then can't (for whatever reason). I've tried updating, uninstalling and re-installing, but still nothing. Any other suggestion?
Cheers.
